Completed test, refactored some things, changed method to return a bo…
Quintor/quindy pull request #11
Opened 2018-09-28 08:38 UTC by daneduijnkerke

…olean on proof verification, fixed createProofFromCredential method to make sure it can create proofs when attributes need to come from a credential in stead of self-attested.

2018-09-28 10:22 UTC, pimotte requested changes
Looks good in general. Couple of small comments. 

Can you also run auto-format with default intellij settings? Especially the lack of spacing between '//' and the comment itself creates some inconsistency.

2018-09-28 10:22 UTC, pimotte commented on src/main/java/nl/quintor/studybits/indy/wrapper/Verifier.java
> +                .thenAccept(result -> ValidateResult(result, "Invalid proof: verifierVerifyProof failed."))
Could you change this function name to match Java style (Yes, I'm aware it was already there :sweat_smile: )

2018-09-28 10:22 UTC, pimotte commented on src/test/java/nl/quintor/studybits/indy/wrapper/MessageScenarioIT.java
> +        //Create proof object from available credenties for this proof request and self-attested attributes
Typo "credenties"

2018-09-28 10:22 UTC, pimotte commented on src/test/java/nl/quintor/studybits/indy/wrapper/MessageScenarioIT.java
> +        if(isValidProof) {
This if seems unnecessary (if it is necessary, the else should probably assert something?)

2018-09-28 10:22 UTC, pimotte commented on src/test/java/nl/quintor/studybits/indy/wrapper/MessageScenarioIT.java
> +        Boolean isValidProof = new Verifier(acmeWallet).validateProof(jobApplicationProofRequest, decryptedProof).get();
I'd make this an unboxed boolean for consistency

2018-09-28 10:22 UTC, pimotte commented on src/test/java/nl/quintor/studybits/indy/wrapper/MessageScenarioIT.java
> +        System.out.println("00000000000000000000000000000000000000: " + decryptedProofRequest);
Remaining debug logging

2018-09-28 10:22 UTC, pimotte commented on src/test/java/nl/quintor/studybits/indy/wrapper/MessageScenarioIT.java
> +        //Steward authenticates Faber #?
Remove "#?" here and line above

2018-09-28 10:22 UTC, pimotte commented on src/test/java/nl/quintor/studybits/indy/wrapper/MessageScenarioIT.java
> +        //#Step 2
Can you add a link to the page where the numbers refer to?

2018-09-28 10:22 UTC, pimotte commented on src/main/java/nl/quintor/studybits/indy/wrapper/util/PoolUtils.java
> +//		PROTOCOL VERSION 2
Please add a TODO marker here "switch to v2"

2018-10-01 10:16 UTC, daneduijnkerke commented
Updated PR based on your feedback

2018-10-02 08:01 UTC, pimotte approved these changes

2018-10-02 08:02 UTC, merged